# Generated by Django 5.1.6 on 2025-02-06 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='num_of_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='num_of_rounds',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('is_drawing', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('is_over', models.BooleanField(default=False)),
                ('round_number', models.IntegerField(default=1)),
                ('time_to_guess', models.IntegerField(default=60)),
                ('current_time', models.IntegerField(default=0)),
                ('current_drawer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
        ),
    ]
